linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - scopelint
    - unconvert
    - unused
    - asciicheck
    # don't enable:
    #- nestif
    #- dupl
    #- goerr113
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - gochecknoinits
